version: '3.3'

services:

  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build: ../company
    restart: unless-stopped
    volumes:
      - media_value:/backend/media/
      - static_value:/backend/static/
    depends_on:
      - db
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/admin"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  media_value:
  static_value:
  postgres_value:
